// Reference directory of Indian engineering institutes, compiled from public
// sources (JoSAA/CSAB participating-institute lists). This is informational
// only — no cutoffs, ranks, or admission predictions are attached, since we
// don't have a verified, current dataset for those. City/state are
// best-known as of compilation; always verify against JoSAA/CSAB or the
// institute's own site before relying on this for an admission decision.

export const COLLEGE_TYPES = {
  IIT: "Indian Institutes of Technology (IITs)",
  NIT: "National Institutes of Technology (NITs)",
  IIIT: "Indian Institutes of Information Technology (IIITs)",
  GFTI: "Government-Funded Technical Institutes (GFTIs)",
  PRIVATE: "Top Private & Deemed Universities",
};

export const COLLEGES = [
  // ── IITs (23) ──────────────────────────────────────────────────────────
  { name: "IIT Bombay", city: "Mumbai", state: "Maharashtra", type: "IIT" },
  { name: "IIT Delhi", city: "New Delhi", state: "Delhi", type: "IIT" },
  { name: "IIT Kanpur", city: "Kanpur", state: "Uttar Pradesh", type: "IIT" },
  { name: "IIT Kharagpur", city: "Kharagpur", state: "West Bengal", type: "IIT" },
  { name: "IIT Madras", city: "Chennai", state: "Tamil Nadu", type: "IIT" },
  { name: "IIT Roorkee", city: "Roorkee", state: "Uttarakhand", type: "IIT" },
  { name: "IIT Guwahati", city: "Guwahati", state: "Assam", type: "IIT" },
  { name: "IIT Hyderabad", city: "Hyderabad", state: "Telangana", type: "IIT" },
  { name: "IIT (BHU) Varanasi", city: "Varanasi", state: "Uttar Pradesh", type: "IIT" },
  { name: "IIT Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "IIT" },
  { name: "IIT Gandhinagar", city: "Gandhinagar", state: "Gujarat", type: "IIT" },
  { name: "IIT Indore", city: "Indore", state: "Madhya Pradesh", type: "IIT" },
  { name: "IIT Jodhpur", city: "Jodhpur", state: "Rajasthan", type: "IIT" },
  { name: "IIT Mandi", city: "Mandi", state: "Himachal Pradesh", type: "IIT" },
  { name: "IIT Patna", city: "Patna", state: "Bihar", type: "IIT" },
  { name: "IIT Ropar", city: "Rupnagar", state: "Punjab", type: "IIT" },
  { name: "IIT (ISM) Dhanbad", city: "Dhanbad", state: "Jharkhand", type: "IIT" },
  { name: "IIT Palakkad", city: "Palakkad", state: "Kerala", type: "IIT" },
  { name: "IIT Tirupati", city: "Tirupati", state: "Andhra Pradesh", type: "IIT" },
  { name: "IIT Bhilai", city: "Bhilai", state: "Chhattisgarh", type: "IIT" },
  { name: "IIT Goa", city: "Ponda", state: "Goa", type: "IIT" },
  { name: "IIT Jammu", city: "Jammu", state: "Jammu & Kashmir", type: "IIT" },
  { name: "IIT Dharwad", city: "Dharwad", state: "Karnataka", type: "IIT" },

  // ── NITs (31) ──────────────────────────────────────────────────────────
  { name: "NIT Trichy", city: "Tiruchirappalli", state: "Tamil Nadu", type: "NIT" },
  { name: "NIT Warangal", city: "Warangal", state: "Telangana", type: "NIT" },
  { name: "NIT Karnataka, Surathkal", city: "Mangalore", state: "Karnataka", type: "NIT" },
  { name: "NIT Rourkela", city: "Rourkela", state: "Odisha", type: "NIT" },
  { name: "NIT Calicut", city: "Kozhikode", state: "Kerala", type: "NIT" },
  { name: "NIT Durgapur", city: "Durgapur", state: "West Bengal", type: "NIT" },
  { name: "NIT Kurukshetra", city: "Kurukshetra", state: "Haryana", type: "NIT" },
  { name: "VNIT Nagpur", city: "Nagpur", state: "Maharashtra", type: "NIT" },
  { name: "MNIT Jaipur", city: "Jaipur", state: "Rajasthan", type: "NIT" },
  { name: "MNNIT Allahabad", city: "Prayagraj", state: "Uttar Pradesh", type: "NIT" },
  { name: "MANIT Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "NIT" },
  { name: "NIT Jamshedpur", city: "Jamshedpur", state: "Jharkhand", type: "NIT" },
  { name: "Dr. B R Ambedkar NIT Jalandhar", city: "Jalandhar", state: "Punjab", type: "NIT" },
  { name: "NIT Silchar", city: "Silchar", state: "Assam", type: "NIT" },
  { name: "NIT Hamirpur", city: "Hamirpur", state: "Himachal Pradesh", type: "NIT" },
  { name: "NIT Patna", city: "Patna", state: "Bihar", type: "NIT" },
  { name: "NIT Raipur", city: "Raipur", state: "Chhattisgarh", type: "NIT" },
  { name: "NIT Srinagar", city: "Srinagar", state: "Jammu & Kashmir", type: "NIT" },
  { name: "NIT Agartala", city: "Agartala", state: "Tripura", type: "NIT" },
  { name: "NIT Arunachal Pradesh", city: "Yupia", state: "Arunachal Pradesh", type: "NIT" },
  { name: "NIT Delhi", city: "New Delhi", state: "Delhi", type: "NIT" },
  { name: "NIT Goa", city: "Ponda", state: "Goa", type: "NIT" },
  { name: "NIT Manipur", city: "Imphal", state: "Manipur", type: "NIT" },
  { name: "NIT Meghalaya", city: "Shillong", state: "Meghalaya", type: "NIT" },
  { name: "NIT Mizoram", city: "Aizawl", state: "Mizoram", type: "NIT" },
  { name: "NIT Nagaland", city: "Dimapur", state: "Nagaland", type: "NIT" },
  { name: "NIT Puducherry", city: "Karaikal", state: "Puducherry", type: "NIT" },
  { name: "NIT Sikkim", city: "Ravangla", state: "Sikkim", type: "NIT" },
  { name: "NIT Uttarakhand", city: "Srinagar (Garhwal)", state: "Uttarakhand", type: "NIT" },
  { name: "NIT Andhra Pradesh", city: "Tadepalligudem", state: "Andhra Pradesh", type: "NIT" },
  { name: "SVNIT Surat", city: "Surat", state: "Gujarat", type: "NIT" },

  // ── IIITs (well-known, 27) ─────────────────────────────────────────────
  { name: "IIIT Hyderabad", city: "Hyderabad", state: "Telangana", type: "IIIT" },
  { name: "IIIT Bangalore", city: "Bangalore", state: "Karnataka", type: "IIIT" },
  { name: "IIIT Delhi", city: "New Delhi", state: "Delhi", type: "IIIT" },
  { name: "IIIT Allahabad", city: "Prayagraj", state: "Uttar Pradesh", type: "IIIT" },
  { name: "ABV-IIITM Gwalior", city: "Gwalior", state: "Madhya Pradesh", type: "IIIT" },
  { name: "IIITDM Jabalpur", city: "Jabalpur", state: "Madhya Pradesh", type: "IIIT" },
  { name: "IIITDM Kancheepuram", city: "Chennai", state: "Tamil Nadu", type: "IIIT" },
  { name: "IIIT Guwahati", city: "Guwahati", state: "Assam", type: "IIIT" },
  { name: "IIIT Kalyani", city: "Kalyani", state: "West Bengal", type: "IIIT" },
  { name: "IIIT Kota", city: "Kota", state: "Rajasthan", type: "IIIT" },
  { name: "IIIT Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "IIIT" },
  { name: "IIIT Nagpur", city: "Nagpur", state: "Maharashtra", type: "IIIT" },
  { name: "IIIT Pune", city: "Pune", state: "Maharashtra", type: "IIIT" },
  { name: "IIIT Ranchi", city: "Ranchi", state: "Jharkhand", type: "IIIT" },
  { name: "IIIT Sonepat", city: "Sonepat", state: "Haryana", type: "IIIT" },
  { name: "IIIT Vadodara", city: "Gandhinagar", state: "Gujarat", type: "IIIT" },
  { name: "IIIT Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "IIIT" },
  { name: "IIIT Bhagalpur", city: "Bhagalpur", state: "Bihar", type: "IIIT" },
  { name: "IIIT Kottayam", city: "Kottayam", state: "Kerala", type: "IIIT" },
  { name: "IIIT Manipur", city: "Imphal", state: "Manipur", type: "IIIT" },
  { name: "IIIT Naya Raipur", city: "Raipur", state: "Chhattisgarh", type: "IIIT" },
  { name: "IIIT Sri City", city: "Chittoor", state: "Andhra Pradesh", type: "IIIT" },
  { name: "IIIT Surat", city: "Surat", state: "Gujarat", type: "IIIT" },
  { name: "IIIT Tiruchirappalli", city: "Tiruchirappalli", state: "Tamil Nadu", type: "IIIT" },
  { name: "IIIT Una", city: "Una", state: "Himachal Pradesh", type: "IIIT" },
  { name: "IIIT Dharwad", city: "Dharwad", state: "Karnataka", type: "IIIT" },
  { name: "IIIT Raichur", city: "Raichur", state: "Karnataka", type: "IIIT" },

  // ── GFTIs & other centrally recognized institutes ─────────────────────
  { name: "IIEST Shibpur", city: "Howrah", state: "West Bengal", type: "GFTI" },
  { name: "Jamia Millia Islamia", city: "New Delhi", state: "Delhi", type: "GFTI" },
  { name: "Birla Institute of Technology, Mesra", city: "Ranchi", state: "Jharkhand", type: "GFTI" },
  { name: "Punjab Engineering College (PEC)", city: "Chandigarh", state: "Chandigarh", type: "GFTI" },
  { name: "Delhi Technological University (DTU)", city: "New Delhi", state: "Delhi", type: "GFTI" },
  { name: "Netaji Subhas University of Technology (NSUT)", city: "New Delhi", state: "Delhi", type: "GFTI" },
  { name: "Central Institute of Technology, Kokrajhar", city: "Kokrajhar", state: "Assam", type: "GFTI" },
  { name: "Indian Institute of Petroleum & Energy", city: "Visakhapatnam", state: "Andhra Pradesh", type: "GFTI" },
  { name: "School of Planning & Architecture, Delhi", city: "New Delhi", state: "Delhi", type: "GFTI" },
  { name: "School of Planning & Architecture, Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "GFTI" },

  // ── Top private / deemed universities widely searched by JEE aspirants ─
  { name: "BITS Pilani", city: "Pilani", state: "Rajasthan", type: "PRIVATE" },
  { name: "BITS Pilani, Goa Campus", city: "Zuarinagar", state: "Goa", type: "PRIVATE" },
  { name: "BITS Pilani, Hyderabad Campus", city: "Hyderabad", state: "Telangana", type: "PRIVATE" },
  { name: "VIT Vellore", city: "Vellore", state: "Tamil Nadu", type: "PRIVATE" },
  { name: "VIT Chennai", city: "Chennai", state: "Tamil Nadu", type: "PRIVATE" },
  { name: "SRM Institute of Science & Technology", city: "Kattankulathur", state: "Tamil Nadu", type: "PRIVATE" },
  { name: "Manipal Institute of Technology", city: "Manipal", state: "Karnataka", type: "PRIVATE" },
  { name: "Thapar Institute of Engineering & Technology", city: "Patiala", state: "Punjab", type: "PRIVATE" },
  { name: "PSG College of Technology", city: "Coimbatore", state: "Tamil Nadu", type: "PRIVATE" },
  { name: "Amrita Vishwa Vidyapeetham", city: "Coimbatore", state: "Tamil Nadu", type: "PRIVATE" },
  { name: "KIIT University", city: "Bhubaneswar", state: "Odisha", type: "PRIVATE" },
  { name: "Lovely Professional University (LPU)", city: "Phagwara", state: "Punjab", type: "PRIVATE" },
];
