// Read-only access to the JoSAA cutoff dataset generated by
// scripts/build-josaa-cutoffs.mjs. Imported at build time by statically
// rendered routes, so the JSON never ships to the client.

import CUTOFFS from "@/app/_data/josaa-cutoffs.json";

export const QUOTA_LABEL = {
  AI: "All India",
  OS: "Other State",
  HS: "Home State",
  GO: "Goa (state quota)",
  JK: "Jammu & Kashmir (state quota)",
  LA: "Ladakh (state quota)",
};

export const TYPE_LABEL = {
  IIT: "Indian Institute of Technology",
  NIT: "National Institute of Technology",
  IIIT: "Indian Institute of Information Technology",
  GFTI: "Government-Funded Technical Institute",
};

export function getAllCutoffColleges() {
  return CUTOFFS;
}

export function getCutoffCollege(slug) {
  return CUTOFFS.find((c) => c.slug === slug) ?? null;
}

export function getCutoffSlugSet() {
  return new Set(CUTOFFS.map((c) => c.slug));
}

/** Latest year present anywhere in the dataset (the "as of" year). */
export function getLatestYear() {
  return CUTOFFS.reduce(
    (max, c) => (c.years.length ? Math.max(max, Number(c.years.at(-1))) : max),
    0,
  );
}
